version: '3.4'

services:
  app:
    build:
      context: .
    image: letscertbot
    volumes:
      - ./config.json:/app/config.json
      - ./tlds.txt:/app/tlds.txt
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt